subat14/kullanici_islemleri/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("giris/",views.giris_islemleri,name="Giris"),
    path("kayit/",views.kayit,name="kayit"),
    path("cikis/",views.cikis,name="cikis"),
]

subat14/subat14/urls.py
from django.contrib import admin
from django.urls import path ,include
from anasayfa.views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",index,name="index"),
    path("ornek/",ornek,name="ornek"),
    path("urungoster/<int:id>",urun_goster,name="urun_goster"),
    path("tekurun/<int:id>",urun_tek_goster,name="tek_urun_goster"),
    path("user/",include("kullanici_islemleri.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subat14/anasayfa/models.py
from django.db import models

# Create your models here.
class ogr(models.Model):
    isim_soyad  = models.CharField(max_length=50)
    def __str__(self):
        return self.isim_soyad
class ogr2(models.Model):
    kategori =  models.ForeignKey(ogr, on_delete=models.CASCADE,null=True)
    isim_soyad = models.CharField(max_length=50)
    aciklama = models.TextField(max_length=250)
    resim = models.FileField(upload_to='kisiresmi/',blank = True,null = True,verbose_name="kisi Resmi Ekleyin")
    def __str__(self):
        return self.isim_soyad

subat14/kullanici_islemleri/models.py
from django.db import models

# Create your models here.

subat14/kullanici_islemleri/forms.py
from django import forms
from django.forms import widgets

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı" , widget=forms.TextInput(attrs={'placeholder': 'Kullanıcı Adı', 'class': 'form-control'}))
    password = forms.CharField(label = "Parola",widget = forms.PasswordInput(attrs={'placeholder': 'Parola', 'class': 'form-control'}))
class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Kullanıcı Adı")
    email = forms.EmailField(max_length=100,label = "Email")
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput)
    def clean(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")
        if password and confirm and password != confirm :
            raise forms.ValidationError("Parolalar Eşleşmiyor")
        
        values = {
            "username" : username,
            "password" : password,
            "email"  : email
        }
        return values

subat14/anasayfa/views.py
from django.shortcuts import render  ,HttpResponse ,redirect
from .models import *
# Create your views here.
def index(request):
    kategori = ogr.objects.all()
    return render(request, "index.html",{"kategori":kategori})

def ornek(request):
    return render(request, "selam.html")

def urun_goster(request,id):
    ogr = ogr2.objects.filter(kategori = id)
    return render(request, "urun_goster.html",{"ogr":ogr})
def urun_tek_goster(request,id):
    obje = ogr2.objects.filter(id = id)
    ogr = ogr2.objects.all()[:3]
    return render(request, "tek_urun.html",{"ogr":ogr,"obj":obje})

subat14/kullanici_islemleri/views.py
from django.shortcuts import render , HttpResponse ,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from .forms import *
# Create your views here.
def giris_islemleri(request):
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            #messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"login.html",context)

        #messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)
def kayit(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        newUser = User(username =username,email=email)
        newUser.set_password(password)
        newUser.save()
        login(request,newUser)
        #messages.info(request,"Başarıyla Kayıt Oldunuz...")
        return redirect("index")
    context = {
            "form" : form
        }
    return render(request,"register.html",context)
def cikis(request):
    logout(request)
    #messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("index")

subat14/anasayfa/templates/content.html
<!-- HOME -->
<div id="home">
    <!-- container -->
    <div class="container">
        <!-- home wrap -->
        <div class="home-wrap">
            <!-- home slick -->
            <div id="home-slick">
                <!-- banner -->
                <div class="banner banner-1">
                    <img src="./img/banner01.jpg" alt="">
                    <div class="banner-caption text-center">
                        <h1>Bags sale</h1>
                        <h3 class="white-color font-weak">Up to 50% Discount</h3>
                        <button class="primary-btn">Shop Now</button>
                    </div>
                </div>
                <!-- /banner -->

                <!-- banner -->
                <div class="banner banner-1">
                    <img src="./img/banner02.jpg" alt="">
                    <div class="banner-caption">
                        <h1 class="primary-color">HOT DEAL<br><span class="white-color font-weak">Up to 50% OFF</span></h1>
                        <button class="primary-btn">Shop Now</button>
                    </div>
                </div>
                <!-- /banner -->

                <!-- banner -->
                <div class="banner banner-1">
                    <img src="./img/banner03.jpg" alt="">
                    <div class="banner-caption">
                        <h1 class="white-color">New Product <span>Collection</span></h1>
                        <button class="primary-btn">Shop Now</button>
                    </div>
                </div>
                <!-- /banner -->
            </div>
            <!-- /home slick -->
        </div>
        <!-- /home wrap -->
    </div>
    <!-- /container -->
</div>
<!-- /HOME -->

subat14/anasayfa/templates/font.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>İlk Django</title>
</head>
<body>
{% for i in ogrenci %}
    <a href="/selam/{{i.id}}"><p>{{i.id}} = {{i.isim_soyad}}</p></a>
{% endfor %}

{% for i in og %}
    <a href="/"><p>{{i.id}} = {{i.isim_soyad}}</p></a>
    <p>{{i.aciklama}}</p>
    {% if i.resim %}
        <img src="{{i.resim.url}}" alt="">
    {% else %}
        <p>Resim Yok</p>
    {% endif %}
    
{% endfor %}
</body>
</html>

subat14/anasayfa/templates/footer.html
<footer id="footer" class="section section-grey">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <!-- footer widget -->
            <div class="col-md-3 col-sm-6 col-xs-6">
                <div class="footer">
                    <!-- footer logo -->
                    <div class="footer-logo">
                        <a class="logo" href="#">
                <img src="./img/logo.png" alt="">
              </a>
                    </div>
                    <!-- /footer logo -->

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>

                    <!-- footer social -->
                    <ul class="footer-social">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                    </ul>
                    <!-- /footer social -->
                </div>
            </div>
            <!-- /footer widget -->

            <!-- footer widget -->
            <div class="col-md-3 col-sm-6 col-xs-6">
                <div class="footer">
                    <h3 class="footer-header">My Account</h3>
                    <ul class="list-links">
                        <li><a href="#">My Account</a></li>
                        <li><a href="#">My Wishlist</a></li>
                        <li><a href="#">Compare</a></li>
                        <li><a href="#">Checkout</a></li>
                        <li><a href="#">Login</a></li>
                    </ul>
                </div>
            </div>
            <!-- /footer widget -->

            <div class="clearfix visible-sm visible-xs"></div>

            <!-- footer widget -->
            <div class="col-md-3 col-sm-6 col-xs-6">
                <div class="footer">
                    <h3 class="footer-header">Customer Service</h3>
                    <ul class="list-links">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Shiping & Return</a></li>
                        <li><a href="#">Shiping Guide</a></li>
                        <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
            </div>
            <!-- /footer widget -->

            <!-- footer subscribe -->
            <div class="col-md-3 col-sm-6 col-xs-6">
                <div class="footer">
                    <h3 class="footer-header">Stay Connected</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
                    <form>
                        <div class="form-group">
                            <input class="input" placeholder="Enter Email Address">
                        </div>
                        <button class="primary-btn">Join Newslatter</button>
                    </form>
                </div>
            </div>
            <!-- /footer subscribe -->
        </div>
        <!-- /row -->
        <hr>
        <!-- row -->
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <!-- footer copyright -->
                <div class="footer-copyright">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
                <!-- /footer copyright -->
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</footer>

subat14/anasayfa/templates/header.html
{% load static %}
<header>
    <!-- top Header -->
    <div id="top-header">
        <div class="container">
            <div class="pull-left">
                <span>Welcome to E-shop!</span>
            </div>
            <div class="pull-right">
                <ul class="header-top-links">
                    <li><a href="#">Store</a></li>
                    <li><a href="#">Newsletter</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li class="dropdown default-dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">ENG <i class="fa fa-caret-down"></i></a>
                        <ul class="custom-menu">
                            <li><a href="#">English (ENG)</a></li>
                            <li><a href="#">Russian (Ru)</a></li>
                            <li><a href="#">French (FR)</a></li>
                            <li><a href="#">Spanish (Es)</a></li>
                        </ul>
                    </li>
                    <li class="dropdown default-dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">USD <i class="fa fa-caret-down"></i></a>
                        <ul class="custom-menu">
                            <li><a href="#">USD ($)</a></li>
                            <li><a href="#">EUR (€)</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /top Header -->

    <!-- header -->
    <div id="header">
        <div class="container">
            <div class="pull-left">
                <!-- Logo -->
                <div class="header-logo">
                    <a class="logo" href="#">
                        <img src="{% static 'img/logo.png' %}" alt="">
                    </a>
                </div>
                <!-- /Logo -->

                <!-- Search -->
                <div class="header-search">
                    <form>
                        <input class="input search-input" type="text" placeholder="Enter your keyword">
                        <select class="input search-categories">
                            <option value="0">All Categories</option>
                            <option value="1">Category 01</option>
                            <option value="1">Category 02</option>
                        </select>
                        <button class="search-btn"><i class="fa fa-search"></i></button>
                    </form>
                </div>
                <!-- /Search -->
            </div>
            <div class="pull-right">
                <ul class="header-btns">
                    <!-- Account -->
                    <li class="header-account dropdown default-dropdown">
                        <div class="dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="true">
                            <div class="header-btns-icon">
                                <i class="fa fa-user-o"></i>
                            </div>
                            <strong class="text-uppercase">Hesabım <i class="fa fa-caret-down"></i></strong>
                        </div>
                        {% if request.user.is_authenticated %}
                        <strong class="text-uppercase">{{request.user}} <i class="fa fa-caret-down"></i></strong>
                        <a href="{% url 'user:cikis' %}" class="text-uppercase">Çıkış</a> 
                        {% else %}
                        <a href="/user/giris/" class="text-uppercase">Giriş</a> / <a href="{% url 'user:kayit' %}" class="text-uppercase">Kayıt</a>
                        {% endif %}
                    </li>
                    <!-- /Account -->

                    <!-- Cart -->
                    <li class="header-cart dropdown default-dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                            <div class="header-btns-icon">
                                <i class="fa fa-shopping-cart"></i>
                                <span class="qty">3</span>
                            </div>
                            <strong class="text-uppercase">My Cart:</strong>
                            <br>
                            <span>35.20$</span>
                        </a>
                        <div class="custom-menu">
                            <div id="shopping-cart">
                                <div class="shopping-cart-list">
                                    <div class="product product-widget">
                                        <div class="product-thumb">
                                            <img src="./img/thumb-product01.jpg" alt="">
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-price">$32.50 <span class="qty">x3</span></h3>
                                            <h2 class="product-name"><a href="#">Product Name Goes Here</a></h2>
                                        </div>
                                        <button class="cancel-btn"><i class="fa fa-trash"></i></button>
                                    </div>
                                    <div class="product product-widget">
                                        <div class="product-thumb">
                                            <img src="./img/thumb-product01.jpg" alt="">
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-price">$32.50 <span class="qty">x3</span></h3>
                                            <h2 class="product-name"><a href="#">Product Name Goes Here</a></h2>
                                        </div>
                                        <button class="cancel-btn"><i class="fa fa-trash"></i></button>
                                    </div>
                                </div>
                                <div class="shopping-cart-btns">
                                    <button class="main-btn">View Cart</button>
                                    <button class="primary-btn">Checkout <i class="fa fa-arrow-circle-right"></i></button>
                                </div>
                            </div>
                        </div>
                    </li>
                    <!-- /Cart -->

                    <!-- Mobile nav toggle-->
                    <li class="nav-toggle">
                        <button class="nav-toggle-btn main-btn icon-btn"><i class="fa fa-bars"></i></button>
                    </li>
                    <!-- / Mobile nav toggle -->
                </ul>
            </div>
        </div>
        <!-- header -->
    </div>
    <!-- container -->
</header>

subat14/anasayfa/templates/homebase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Hind:400,700" rel="stylesheet">

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

	<!-- Slick -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}" />

	<!-- nouislider -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}" />

	<!-- Font Awesome Icon -->
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	{% block head %}
	<title>E-SHOP HTML Template</title>
	{% endblock head %}
</head>

<body>
	{% block header %}
		{% include "header.html" %}
	{% endblock header %}

	{% block slider %}
		
	{% endblock slider %}
	
	{% block content %}
		
	{% endblock content %}
	
	{% block sidebar %}
		
	{% endblock sidebar %}
	<!-- section -->
	
	{% block footer %}
		{% include "footer.html" %}
	{% endblock footer %}
	<!-- FOOTER -->

	<!-- /FOOTER -->

	<!-- jQuery Plugins -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

subat14/anasayfa/templates/index.html
{% extends "homebase.html" %}
{% block head %}
<title>E-Shop Anasayafa</title>
{% endblock head %}
{% block slider %}
		{% include "slider.html" %}
	{% endblock slider %}
	
	{% block content %}
		{% include "content.html" %}
	{% endblock content %}
	
	{% block sidebar %}
		{% include "sidebar.html" %}
	{% endblock sidebar %}

subat14/anasayfa/templates/login.html
{% extends "homebase.html" %}
{% block head %}
<title>E-Shop Login</title>
{% endblock head %}
{% block slider %}
<div class="hero-image" id="full-width">
    <div class="hero-text-form">
        <form class="text-center"  method="POST">
            <h3>Lütfen Giriş Yapınız</h3>
            {% csrf_token %}
            <div class="form-floating mb-3">
                {{ form}}
            </div>
            

            <br />
            
            <button type="submit" class="btn btn-lg btn-success">
                Giriş Yap
            </button>
        </form>
    </div>
</div>
<!--**hero image-->
	{% endblock slider %}

subat14/anasayfa/templates/register.html
{% extends "homebase.html" %}
{% block head %}
<title>E-Shop Login</title>
{% endblock head %}
{% block slider %}
<div class="hero-image" id="full-width">
    <div class="hero-text-form">
        <form class="text-center"  method="POST">
            <h3>Lütfen Giriş Yapınız</h3>
            {% csrf_token %}
            <div class="form-floating mb-3">
                {{ form}}
            </div>
            

            <br />
            
            <button type="submit" class="btn btn-lg btn-success">
                Üye Ol
            </button>
        </form>
    </div>
</div>
<!--**hero image-->
	{% endblock slider %}

subat14/anasayfa/templates/selam.html
{% extends "homebase.html" %}